In [2]:
import tensorflow as tf

In [5]:
#从均匀分布中输出随机值
img = tf.random_uniform([10,28,28,3])
with tf.Session() as sess1:
    print(sess1.run(img))

[[[[3.72261405e-01 5.78997970e-01 1.79065585e-01]
   [2.83610225e-01 7.55720854e-01 8.55740547e-01]
   [4.18836117e-01 3.72050285e-01 5.49307585e-01]
   ...
   [6.56572223e-01 3.79636526e-01 4.58835602e-01]
   [4.92488623e-01 8.25492382e-01 8.09164166e-01]
   [6.09712124e-01 9.44777012e-01 2.26890087e-01]]

  [[9.65977073e-01 9.15165544e-01 4.62140083e-01]
   [3.36571574e-01 9.86973166e-01 2.71275043e-01]
   [7.07579851e-01 4.92545605e-01 8.79873872e-01]
   ...
   [7.62649775e-01 5.20984530e-01 5.29660940e-01]
   [3.66731882e-01 9.56164837e-01 4.42263722e-01]
   [4.41072106e-01 3.13095570e-01 2.13597536e-01]]

  [[4.62130547e-01 9.50748324e-01 4.64410543e-01]
   [1.93736196e-01 1.96355224e-01 8.10256004e-01]
   [2.56585240e-01 8.95850182e-01 5.11413574e-01]
   ...
   [3.62430811e-02 9.44251180e-01 4.40272093e-02]
   [1.04148626e-01 7.92964697e-01 5.43094993e-01]
   [7.11403728e-01 8.02214146e-02 8.87330651e-01]]

  ...

  [[6.89244151e-01 9.87637401e-01 4.70233798e-01]
   [8.59336376e-

In [7]:
#利用索引取出第二张图片
a = img[1:2,0:,0:,0:]
with tf.Session() as sess2:
    print(sess2.run(a))

[[[[0.7044717  0.56305933 0.59675777]
   [0.10826921 0.14541829 0.99998355]
   [0.19036794 0.6388142  0.18827975]
   ...
   [0.69096816 0.5754274  0.46310103]
   [0.851454   0.01390004 0.9771069 ]
   [0.6254686  0.38969386 0.74382055]]

  [[0.8316624  0.57861423 0.03388071]
   [0.69713163 0.09695804 0.29731894]
   [0.5387013  0.31259763 0.63625014]
   ...
   [0.02976251 0.11183548 0.8488407 ]
   [0.61507297 0.540696   0.65939593]
   [0.8775312  0.7885785  0.67879844]]

  [[0.7043942  0.86160946 0.85186183]
   [0.33105373 0.740211   0.11554575]
   [0.97031546 0.95496976 0.894567  ]
   ...
   [0.6915115  0.10052872 0.00707233]
   [0.45630813 0.36613917 0.4611659 ]
   [0.19869685 0.39520025 0.57479846]]

  ...

  [[0.4777317  0.48944724 0.6310872 ]
   [0.95624983 0.3515439  0.3128556 ]
   [0.2584499  0.415915   0.93155396]
   ...
   [0.3819337  0.5927566  0.06320405]
   [0.01895475 0.09574223 0.06212616]
   [0.264192   0.68022406 0.8470359 ]]

  [[0.976804   0.04470944 0.7102848 ]
   [0.3

In [22]:
#利用切片取出第二张图片
b = tf.slice(img,[1,0,0,0],[1,28,28,3])
with tf.Session() as sess3:
    print(sess3.run(b))

[[[[0.7731507  0.67819965 0.31175005]
   [0.08489406 0.9151679  0.40227234]
   [0.24908328 0.54589844 0.830781  ]
   ...
   [0.91540277 0.26596928 0.34656703]
   [0.39403474 0.24006462 0.802385  ]
   [0.48207462 0.7002673  0.9192779 ]]

  [[0.13560128 0.66827786 0.61818767]
   [0.8979398  0.93397486 0.4523642 ]
   [0.97483647 0.8415618  0.96207356]
   ...
   [0.6525279  0.7100569  0.4593135 ]
   [0.87020624 0.15365481 0.88569355]
   [0.4821589  0.5243852  0.0794661 ]]

  [[0.63314927 0.12411177 0.1251055 ]
   [0.8668146  0.39234793 0.3094802 ]
   [0.37586462 0.39800072 0.39590228]
   ...
   [0.82985246 0.96448696 0.4797455 ]
   [0.3478092  0.01733816 0.15482378]
   [0.20679009 0.89572215 0.22915149]]

  ...

  [[0.3317026  0.11333275 0.34505796]
   [0.35638416 0.770031   0.37549472]
   [0.1808579  0.849103   0.73088586]
   ...
   [0.14903569 0.818782   0.7191825 ]
   [0.16199386 0.8666221  0.79960537]
   [0.8297875  0.11518371 0.19871092]]

  [[0.8054588  0.68568325 0.38629282]
   [0.6

In [12]:
#使用切片和索引取出图片的不同
#切片是原始数据的视图，而索引是取出的真实数据

In [15]:
#取出1357张图片
for i in range (1,4):
    j=1
    c = tf.slice(img,[j-1,0,0,0],[1,28,28,3]) 
    j=j+2
    with tf.Session() as sess4:
        print(sess4.run(c))

[[[[0.30009353 0.68507767 0.9890038 ]
   [0.17515767 0.8918233  0.04483926]
   [0.06991959 0.1547203  0.28722095]
   ...
   [0.11708796 0.18346298 0.8068315 ]
   [0.60004675 0.52968943 0.60705626]
   [0.24410677 0.55651605 0.8606527 ]]

  [[0.45754778 0.77087    0.4181249 ]
   [0.22054017 0.6110722  0.19951141]
   [0.9441116  0.36825657 0.8522861 ]
   ...
   [0.3400141  0.33190405 0.675496  ]
   [0.41743147 0.93006563 0.8296988 ]
   [0.4145826  0.8961506  0.42397928]]

  [[0.5396756  0.93208754 0.7103226 ]
   [0.14204788 0.73704183 0.15839171]
   [0.25722933 0.6536267  0.86028576]
   ...
   [0.5560008  0.8911823  0.9117304 ]
   [0.8986933  0.6309166  0.6239381 ]
   [0.6088728  0.999557   0.4391588 ]]

  ...

  [[0.14461541 0.9781226  0.27084124]
   [0.8570894  0.43388867 0.30014443]
   [0.28481162 0.96923983 0.8280963 ]
   ...
   [0.6703328  0.89297926 0.9722476 ]
   [0.35017502 0.3137871  0.81835747]
   [0.080127   0.47515476 0.12360287]]

  [[0.06067395 0.37824    0.812037  ]
   [0.3

In [16]:
#第七张中心区域
d = tf.slice(img,[6,7,7,0],[1,14,14,3])
with tf.Session() as sess5:
    print(sess5.run(d))

[[[[9.14694548e-01 3.30254912e-01 4.40951586e-01]
   [4.40569639e-01 8.37721825e-01 5.29361486e-01]
   [6.56860828e-01 4.91733432e-01 7.76346684e-01]
   [1.87370420e-01 3.02861333e-01 8.20237398e-02]
   [2.87554026e-01 3.54504347e-01 4.32452321e-01]
   [2.07363963e-01 5.43806314e-01 2.70884037e-01]
   [9.31293130e-01 1.40962243e-01 5.07221103e-01]
   [5.59833407e-01 7.24008083e-02 2.46589303e-01]
   [2.47204304e-03 1.83569312e-01 8.24182987e-01]
   [7.05300450e-01 6.47012353e-01 2.13656664e-01]
   [5.08676887e-01 7.70294070e-01 8.61963153e-01]
   [4.12600994e-01 8.90853882e-01 3.78329396e-01]
   [7.54897594e-02 7.71582007e-01 5.06085277e-01]
   [4.22019005e-01 1.79685473e-01 6.18793249e-01]]

  [[8.53999138e-01 3.60424876e-01 7.29810357e-01]
   [2.67025113e-01 6.22894287e-01 2.35853434e-01]
   [1.48024201e-01 6.68181419e-01 6.79759741e-01]
   [1.57840133e-01 3.35563302e-01 2.63711691e-01]
   [6.38706803e-01 8.10634017e-01 7.91065574e-01]
   [1.48256898e-01 1.99155807e-01 1.76054239e-02

In [18]:
#三份单通道图片
e = tf.slice(img,[0,0,0,0],[10,28,28,1])
f = tf.slice(img,[0,0,0,1],[10,28,28,1])
g = tf.slice(img,[0,0,0,2],[10,28,28,1])
with tf.Session() as sess6:
    print(sess6.run(e))
with tf.Session() as sess7:
    print(sess7.run(f))
with tf.Session() as sess8:
    print(sess8.run(g))

[[[[0.7477987 ]
   [0.2193346 ]
   [0.5783334 ]
   ...
   [0.01784122]
   [0.710904  ]
   [0.9942167 ]]

  [[0.2708001 ]
   [0.9204626 ]
   [0.20481527]
   ...
   [0.92950296]
   [0.42920125]
   [0.40858018]]

  [[0.31704795]
   [0.43396544]
   [0.7218654 ]
   ...
   [0.67564726]
   [0.6790103 ]
   [0.45822394]]

  ...

  [[0.5408577 ]
   [0.5299926 ]
   [0.78602827]
   ...
   [0.40822053]
   [0.42064512]
   [0.30824196]]

  [[0.35897768]
   [0.6073955 ]
   [0.14061415]
   ...
   [0.30225945]
   [0.21749854]
   [0.4151733 ]]

  [[0.944844  ]
   [0.40669572]
   [0.196208  ]
   ...
   [0.5343194 ]
   [0.35398054]
   [0.07710743]]]


 [[[0.16823101]
   [0.61173   ]
   [0.9135816 ]
   ...
   [0.7513778 ]
   [0.06057978]
   [0.5252857 ]]

  [[0.796942  ]
   [0.4273398 ]
   [0.99366593]
   ...
   [0.65271306]
   [0.49269378]
   [0.8423468 ]]

  [[0.9116591 ]
   [0.35104728]
   [0.64052176]
   ...
   [0.39783692]
   [0.996436  ]
   [0.1953566 ]]

  ...

  [[0.09602582]
   [0.81026745]
   [0.3

In [22]:
#4阶，shape(10,28,28,3)